const menu = [
    {
      id: 1,
      title: 'Poke Original',
      category: 'Poke',
      price: 22.99,
      img: './images/Pratos/item-1.jpg',
      desc: `
      Salmão fresco, arroz japonês, molho Easy Poke (laranja, gengibre e caramelo), tomate cereja, sunomono (pepino agridoce), cenoura, crisp de alho poró e amendoim.`,
    },
    {
      id: 2,
      title: 'Poke Classic',
      category: 'Poke',
      price: 27.99,
      img: './images/Pratos/item-2.jpg',
      desc: `
      Salmão fresco, arroz japonês, molho Easy Poke (laranja, gengibre e caramelo), tomate cereja, sunomono (pepino agridoce), cenoura, crisp de alho poró e amendoim.`,
    },
    {
      id: 3,
      title: 'Poke Fresh',
      category: 'Poke',
      price: 29.99,
      img: './images/Pratos/item-3.jpg',
      desc: `
      Salmão fresco, arroz japonês, molho Easy Poke (laranja, gengibre e caramelo), tomate cereja, sunomono (pepino agridoce), cenoura, crisp de alho poró e amendoim.`,
    },
    {
      id: 4,
      title: 'Poke Fit',
      category: 'Poke',
      price: 22.99,
      img: './images/Pratos/item-4.jpg',
      desc: `
      Salmão fresco, arroz japonês, molho Easy Poke (laranja, gengibre e caramelo), tomate cereja, sunomono (pepino agridoce), cenoura, crisp de alho poró e amendoim.`,
    },
    {
      id: 5,
      title: 'Poke Family',
      category: 'Poke',
      price: 22.99,
      img: './images/Pratos/item-5.jpg',
      desc: `
      Salmão fresco, arroz japonês, molho Easy Poke (laranja, gengibre e caramelo), tomate cereja, sunomono (pepino agridoce), cenoura, crisp de alho poró e amendoim.`,
    },
    {
      id: 6,
      title: 'Poke Fruit',
      category: 'Poke',
      price: 18.99,
      img: './images/Pratos/item-6.jpg',
      desc: `
      Salmão fresco, arroz japonês, molho Easy Poke (laranja, gengibre e caramelo), tomate cereja, sunomono (pepino agridoce), cenoura, crisp de alho poró e amendoim.`,
    },
    {
      id: 7,
      title: 'Salmao',
      category: 'Monte',
      price: 14.99,
      img: './images/Pratos/item-14.jpg',
      desc: `Um Milkshake Insano como você nunca viu! A combinação de baunilha com macadâmia caramelizada e muita calda de caramelo. Uma explosão de sabor e cremosidade.`,
    },
    {
      id: 8,
      title: 'Salmão cru',
      category: 'Monte',
      price: 14.99,
      img: './images/Pratos/item-14.jpg',
      desc: `Um Milkshake Insano como você nunca viu! A combinação de baunilha com macadâmia caramelizada e muita calda de caramelo. Uma explosão de sabor e cremosidade.`,
    },
    {
      id: 9,
      title: 'Atum',
      category: 'Monte',
      price: 14.99,
      img: './images/Pratos/item-14.jpg',
      desc: `Um Milkshake Insano como você nunca viu! A combinação de baunilha com macadâmia caramelizada e muita calda de caramelo. Uma explosão de sabor e cremosidade.`,
    },
    {
      id: 10,
      title: 'Frango',
      category: 'Monte',
      price: 14.99,
      img: './images/Pratos/item-14.jpg',
      desc: `Um Milkshake Insano como você nunca viu! A combinação de baunilha com macadâmia caramelizada e muita calda de caramelo. Uma explosão de sabor e cremosidade.`,
    },
    {
      id: 11,
      title: 'Batata Chips',
      category: 'Monte',
      price: 14.99,
      img: './images/Pratos/item-14.jpg',
      desc: `Um Milkshake Insano como você nunca viu! A combinação de baunilha com macadâmia caramelizada e muita calda de caramelo. Uma explosão de sabor e cremosidade.`,
    },
    {
      id: 12,
      title: 'Arroz',
      category: 'Monte',
      price: 14.99,
      img: './images/Pratos/item-14.jpg',
      desc: `Um Milkshake Insano como você nunca viu! A combinação de baunilha com macadâmia caramelizada e muita calda de caramelo. Uma explosão de sabor e cremosidade.`,
    },
    {
      id: 13,
      title: 'Temaki Philadelphia Completo',
      category: 'Temaki',
      price: 24.99,
      img: './images/Pratos/item-13.jpg',
      desc: `Pão com gergelim, um saboroso hambúrguer de pura carne bovina, uma fatia de queijo derretido, duas fatias de picles, ketchup e mostarda.`,
    },
    {
      id: 14,
      title: 'Temaki Philadelphia',
      category: 'Temaki',
      price: 24.99,
      img: './images/Pratos/item-14.jpg',
      desc: `Pão com gergelim, um saboroso hambúrguer de pura carne bovina, uma fatia de queijo derretido, duas fatias de picles, ketchup e mostarda.`,
    },
    {
      id: 15,
      title: 'Temaki Shimeji',
      category: 'Temaki',
      price: 24.99,
      img: './images/Pratos/item-15.jpg',
      desc: `Pão com gergelim, um saboroso hambúrguer de pura carne bovina, uma fatia de queijo derretido, duas fatias de picles, ketchup e mostarda.`,
    },
  ];
  export default menu;